// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pixel_dma_in_pixel_dma_in,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=6.667000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.866910,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=0,HLS_SYN_FF=5534,HLS_SYN_LUT=5487,HLS_VERSION=2022_1}" *)

module pixel_dma_in (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        axis_pixel_out_TDATA,
        axis_pixel_out_TVALID,
        axis_pixel_out_TREADY,
        axis_pixel_out_TKEEP,
        axis_pixel_out_TSTRB,
        axis_pixel_out_TLAST,
        s_axi_AXI_Lite_1_AWVALID,
        s_axi_AXI_Lite_1_AWREADY,
        s_axi_AXI_Lite_1_AWADDR,
        s_axi_AXI_Lite_1_WVALID,
        s_axi_AXI_Lite_1_WREADY,
        s_axi_AXI_Lite_1_WDATA,
        s_axi_AXI_Lite_1_WSTRB,
        s_axi_AXI_Lite_1_ARVALID,
        s_axi_AXI_Lite_1_ARREADY,
        s_axi_AXI_Lite_1_ARADDR,
        s_axi_AXI_Lite_1_RVALID,
        s_axi_AXI_Lite_1_RREADY,
        s_axi_AXI_Lite_1_RDATA,
        s_axi_AXI_Lite_1_RRESP,
        s_axi_AXI_Lite_1_BVALID,
        s_axi_AXI_Lite_1_BREADY,
        s_axi_AXI_Lite_1_BRESP,
        interrupt,
        axi_lite_clk,
        ap_rst_n_axi_lite_clk
);

parameter    ap_ST_fsm_state1 = 41'd1;
parameter    ap_ST_fsm_state2 = 41'd2;
parameter    ap_ST_fsm_state3 = 41'd4;
parameter    ap_ST_fsm_state4 = 41'd8;
parameter    ap_ST_fsm_state5 = 41'd16;
parameter    ap_ST_fsm_state6 = 41'd32;
parameter    ap_ST_fsm_state7 = 41'd64;
parameter    ap_ST_fsm_state8 = 41'd128;
parameter    ap_ST_fsm_state9 = 41'd256;
parameter    ap_ST_fsm_state10 = 41'd512;
parameter    ap_ST_fsm_state11 = 41'd1024;
parameter    ap_ST_fsm_state12 = 41'd2048;
parameter    ap_ST_fsm_state13 = 41'd4096;
parameter    ap_ST_fsm_state14 = 41'd8192;
parameter    ap_ST_fsm_state15 = 41'd16384;
parameter    ap_ST_fsm_state16 = 41'd32768;
parameter    ap_ST_fsm_state17 = 41'd65536;
parameter    ap_ST_fsm_state18 = 41'd131072;
parameter    ap_ST_fsm_state19 = 41'd262144;
parameter    ap_ST_fsm_state20 = 41'd524288;
parameter    ap_ST_fsm_state21 = 41'd1048576;
parameter    ap_ST_fsm_state22 = 41'd2097152;
parameter    ap_ST_fsm_state23 = 41'd4194304;
parameter    ap_ST_fsm_state24 = 41'd8388608;
parameter    ap_ST_fsm_state25 = 41'd16777216;
parameter    ap_ST_fsm_state26 = 41'd33554432;
parameter    ap_ST_fsm_state27 = 41'd67108864;
parameter    ap_ST_fsm_state28 = 41'd134217728;
parameter    ap_ST_fsm_state29 = 41'd268435456;
parameter    ap_ST_fsm_state30 = 41'd536870912;
parameter    ap_ST_fsm_state31 = 41'd1073741824;
parameter    ap_ST_fsm_state32 = 41'd2147483648;
parameter    ap_ST_fsm_state33 = 41'd4294967296;
parameter    ap_ST_fsm_state34 = 41'd8589934592;
parameter    ap_ST_fsm_state35 = 41'd17179869184;
parameter    ap_ST_fsm_state36 = 41'd34359738368;
parameter    ap_ST_fsm_state37 = 41'd68719476736;
parameter    ap_ST_fsm_state38 = 41'd137438953472;
parameter    ap_ST_fsm_state39 = 41'd274877906944;
parameter    ap_ST_fsm_state40 = 41'd549755813888;
parameter    ap_ST_fsm_state41 = 41'd1099511627776;
parameter    C_S_AXI_AXI_LITE_1_DATA_WIDTH = 32;
parameter    C_S_AXI_AXI_LITE_1_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXI_LITE_1_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
output  [31:0] axis_pixel_out_TDATA;
output   axis_pixel_out_TVALID;
input   axis_pixel_out_TREADY;
output  [3:0] axis_pixel_out_TKEEP;
output  [3:0] axis_pixel_out_TSTRB;
output  [0:0] axis_pixel_out_TLAST;
input   s_axi_AXI_Lite_1_AWVALID;
output   s_axi_AXI_Lite_1_AWREADY;
input  [C_S_AXI_AXI_LITE_1_ADDR_WIDTH - 1:0] s_axi_AXI_Lite_1_AWADDR;
input   s_axi_AXI_Lite_1_WVALID;
output   s_axi_AXI_Lite_1_WREADY;
input  [C_S_AXI_AXI_LITE_1_DATA_WIDTH - 1:0] s_axi_AXI_Lite_1_WDATA;
input  [C_S_AXI_AXI_LITE_1_WSTRB_WIDTH - 1:0] s_axi_AXI_Lite_1_WSTRB;
input   s_axi_AXI_Lite_1_ARVALID;
output   s_axi_AXI_Lite_1_ARREADY;
input  [C_S_AXI_AXI_LITE_1_ADDR_WIDTH - 1:0] s_axi_AXI_Lite_1_ARADDR;
output   s_axi_AXI_Lite_1_RVALID;
input   s_axi_AXI_Lite_1_RREADY;
output  [C_S_AXI_AXI_LITE_1_DATA_WIDTH - 1:0] s_axi_AXI_Lite_1_RDATA;
output  [1:0] s_axi_AXI_Lite_1_RRESP;
output   s_axi_AXI_Lite_1_BVALID;
input   s_axi_AXI_Lite_1_BREADY;
output  [1:0] s_axi_AXI_Lite_1_BRESP;
output   interrupt;
input   axi_lite_clk;
input   ap_rst_n_axi_lite_clk;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [40:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] axi_pixel_in;
wire   [31:0] frame_width;
wire   [31:0] frame_height;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state12;
reg   [0:0] cmp46_reg_528;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state30;
reg   [31:0] frame_height_read_reg_471;
reg   [31:0] axi_pixel_in_read_reg_476;
wire   [4:0] empty_fu_233_p1;
reg   [4:0] empty_reg_484;
wire   [29:0] empty_34_fu_237_p1;
reg   [29:0] empty_34_reg_490;
wire  signed [29:0] empty_35_fu_247_p2;
reg   [29:0] empty_35_reg_496;
reg   [26:0] trunc_ln_reg_502;
wire   [28:0] trunc_ln68_fu_263_p1;
reg   [28:0] trunc_ln68_reg_507;
reg   [24:0] tmp_2_reg_512;
wire   [29:0] and_ln_fu_282_p3;
reg   [29:0] and_ln_reg_517;
wire    ap_CS_fsm_state2;
wire   [29:0] add_ln68_1_fu_289_p2;
reg   [29:0] add_ln68_1_reg_522;
wire   [0:0] cmp46_fu_294_p2;
wire    ap_CS_fsm_state3;
wire   [4:0] add_ln68_fu_299_p2;
reg   [4:0] add_ln68_reg_532;
wire   [29:0] shl_ln_fu_304_p3;
reg   [29:0] shl_ln_reg_537;
wire   [29:0] tmp_fu_311_p2;
reg   [29:0] tmp_reg_542;
wire   [31:0] indvars_iv_next262_fu_323_p2;
reg   [31:0] indvars_iv_next262_reg_550;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln68_fu_318_p2;
wire   [29:0] grp_fu_333_p2;
reg   [29:0] empty_36_reg_560;
wire    ap_CS_fsm_state8;
wire   [29:0] empty_37_fu_343_p2;
reg   [29:0] empty_37_reg_569;
wire    ap_CS_fsm_state9;
wire   [29:0] empty_39_fu_353_p2;
reg   [29:0] empty_39_reg_574;
wire   [29:0] empty_41_fu_358_p2;
reg   [29:0] empty_41_reg_579;
wire   [29:0] add_ln72_6_fu_362_p2;
reg   [29:0] add_ln72_6_reg_584;
wire   [31:0] empty_38_fu_373_p2;
reg   [31:0] empty_38_reg_589;
wire    ap_CS_fsm_state10;
wire   [31:0] empty_40_fu_385_p2;
reg   [31:0] empty_40_reg_594;
wire   [31:0] empty_42_fu_397_p2;
reg   [31:0] empty_42_reg_599;
wire  signed [29:0] trunc_ln4_fu_402_p4;
reg   [29:0] trunc_ln4_reg_604;
reg   [29:0] trunc_ln5_reg_614;
reg   [29:0] trunc_ln6_reg_620;
reg   [4:0] buf0_address0;
reg    buf0_ce0;
reg    buf0_we0;
reg   [31:0] buf0_d0;
wire   [31:0] buf0_q0;
reg   [4:0] buf1_address0;
reg    buf1_ce0;
reg    buf1_we0;
reg   [31:0] buf1_d0;
wire   [31:0] buf1_q0;
reg   [4:0] buf2_address0;
reg    buf2_ce0;
reg    buf2_we0;
reg   [31:0] buf2_d0;
wire   [31:0] buf2_q0;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_start;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_done;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_idle;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_ready;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWVALID;
wire   [31:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWADDR;
wire   [0:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWID;
wire   [31:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWLEN;
wire   [2:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWSIZE;
wire   [1:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWBURST;
wire   [1:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWLOCK;
wire   [3:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWCACHE;
wire   [2:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWPROT;
wire   [3:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWQOS;
wire   [3:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWREGION;
wire   [0:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWUSER;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_WVALID;
wire   [31:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_WDATA;
wire   [3:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_WSTRB;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_WLAST;
wire   [0:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_WID;
wire   [0:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_WUSER;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARVALID;
wire   [31:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARADDR;
wire   [0:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARID;
wire   [31:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARLEN;
wire   [2:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARSIZE;
wire   [1:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARBURST;
wire   [1:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARLOCK;
wire   [3:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARCACHE;
wire   [2:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARPROT;
wire   [3:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARQOS;
wire   [3:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARREGION;
wire   [0:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARUSER;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_RREADY;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_BREADY;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TREADY;
wire   [4:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf2_address0;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf2_ce0;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf2_we0;
wire   [31:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf2_d0;
wire   [4:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf1_address0;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf1_ce0;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf1_we0;
wire   [31:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf1_d0;
wire   [4:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf0_address0;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf0_ce0;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf0_we0;
wire   [31:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf0_d0;
wire   [31:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TDATA;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TVALID;
wire   [3:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TKEEP;
wire   [3:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TSTRB;
wire   [0:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TLAST;
wire    grp_pixel_dma_in_Pipeline_2_fu_193_ap_start;
wire    grp_pixel_dma_in_Pipeline_2_fu_193_ap_done;
wire    grp_pixel_dma_in_Pipeline_2_fu_193_ap_idle;
wire    grp_pixel_dma_in_Pipeline_2_fu_193_ap_ready;
wire    grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWVALID;
wire   [31:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWADDR;
wire   [0:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWID;
wire   [31:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWLEN;
wire   [2:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWSIZE;
wire   [1:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWBURST;
wire   [1:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWLOCK;
wire   [3:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWCACHE;
wire   [2:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWPROT;
wire   [3:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWQOS;
wire   [3:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWREGION;
wire   [0:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWUSER;
wire    grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_WVALID;
wire   [31:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_WDATA;
wire   [3:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_WSTRB;
wire    grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_WLAST;
wire   [0:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_WID;
wire   [0:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_WUSER;
wire    grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARVALID;
wire   [31:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARADDR;
wire   [0:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARID;
wire   [31:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARLEN;
wire   [2:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARSIZE;
wire   [1:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARBURST;
wire   [1:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARLOCK;
wire   [3:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARCACHE;
wire   [2:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARPROT;
wire   [3:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARQOS;
wire   [3:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARREGION;
wire   [0:0] grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARUSER;
wire    grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_RREADY;
wire    grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_BREADY;
wire   [4:0] grp_pixel_dma_in_Pipeline_2_fu_193_buf0_address0;
wire    grp_pixel_dma_in_Pipeline_2_fu_193_buf0_ce0;
wire    grp_pixel_dma_in_Pipeline_2_fu_193_buf0_we0;
wire   [31:0] grp_pixel_dma_in_Pipeline_2_fu_193_buf0_d0;
wire    grp_pixel_dma_in_Pipeline_3_fu_201_ap_start;
wire    grp_pixel_dma_in_Pipeline_3_fu_201_ap_done;
wire    grp_pixel_dma_in_Pipeline_3_fu_201_ap_idle;
wire    grp_pixel_dma_in_Pipeline_3_fu_201_ap_ready;
wire    grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWVALID;
wire   [31:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWADDR;
wire   [0:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWID;
wire   [31:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWLEN;
wire   [2:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWSIZE;
wire   [1:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWBURST;
wire   [1:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWLOCK;
wire   [3:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWCACHE;
wire   [2:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWPROT;
wire   [3:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWQOS;
wire   [3:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWREGION;
wire   [0:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWUSER;
wire    grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_WVALID;
wire   [31:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_WDATA;
wire   [3:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_WSTRB;
wire    grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_WLAST;
wire   [0:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_WID;
wire   [0:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_WUSER;
wire    grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARVALID;
wire   [31:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARADDR;
wire   [0:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARID;
wire   [31:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARLEN;
wire   [2:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARSIZE;
wire   [1:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARBURST;
wire   [1:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARLOCK;
wire   [3:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARCACHE;
wire   [2:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARPROT;
wire   [3:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARQOS;
wire   [3:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARREGION;
wire   [0:0] grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARUSER;
wire    grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_RREADY;
wire    grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_BREADY;
wire   [4:0] grp_pixel_dma_in_Pipeline_3_fu_201_buf1_address0;
wire    grp_pixel_dma_in_Pipeline_3_fu_201_buf1_ce0;
wire    grp_pixel_dma_in_Pipeline_3_fu_201_buf1_we0;
wire   [31:0] grp_pixel_dma_in_Pipeline_3_fu_201_buf1_d0;
wire    grp_pixel_dma_in_Pipeline_4_fu_209_ap_start;
wire    grp_pixel_dma_in_Pipeline_4_fu_209_ap_done;
wire    grp_pixel_dma_in_Pipeline_4_fu_209_ap_idle;
wire    grp_pixel_dma_in_Pipeline_4_fu_209_ap_ready;
wire    grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWVALID;
wire   [31:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWADDR;
wire   [0:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWID;
wire   [31:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWLEN;
wire   [2:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWSIZE;
wire   [1:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWBURST;
wire   [1:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWLOCK;
wire   [3:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWCACHE;
wire   [2:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWPROT;
wire   [3:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWQOS;
wire   [3:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWREGION;
wire   [0:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWUSER;
wire    grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_WVALID;
wire   [31:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_WDATA;
wire   [3:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_WSTRB;
wire    grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_WLAST;
wire   [0:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_WID;
wire   [0:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_WUSER;
wire    grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARVALID;
wire   [31:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARADDR;
wire   [0:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARID;
wire   [31:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARLEN;
wire   [2:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARSIZE;
wire   [1:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARBURST;
wire   [1:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARLOCK;
wire   [3:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARCACHE;
wire   [2:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARPROT;
wire   [3:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARQOS;
wire   [3:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARREGION;
wire   [0:0] grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARUSER;
wire    grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_RREADY;
wire    grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_BREADY;
wire   [4:0] grp_pixel_dma_in_Pipeline_4_fu_209_buf2_address0;
wire    grp_pixel_dma_in_Pipeline_4_fu_209_buf2_ce0;
wire    grp_pixel_dma_in_Pipeline_4_fu_209_buf2_we0;
wire   [31:0] grp_pixel_dma_in_Pipeline_4_fu_209_buf2_d0;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_start;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_done;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_idle;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_ready;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TREADY;
wire   [4:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf0_address0;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf0_ce0;
wire   [31:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TDATA;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TVALID;
wire   [3:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TKEEP;
wire   [3:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TSTRB;
wire   [0:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TLAST;
wire   [4:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf1_address0;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf1_ce0;
wire   [4:0] grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf2_address0;
wire    grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf2_ce0;
reg    ap_rst_n_axi_lite_clk_inv;
wire    gmem_AWREADY;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [31:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_pixel_dma_in_Pipeline_2_fu_193_ap_start_reg;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
reg    grp_pixel_dma_in_Pipeline_3_fu_201_ap_start_reg;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
reg    grp_pixel_dma_in_Pipeline_4_fu_209_ap_start_reg;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state38;
reg    grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_start_reg;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state40;
wire  signed [31:0] sext_ln93_fu_411_p1;
wire  signed [31:0] sext_ln94_fu_440_p1;
wire  signed [31:0] sext_ln95_fu_450_p1;
reg    ap_block_state12_io;
reg   [31:0] i_fu_116;
reg    ap_block_state40_on_subcall_done;
wire   [31:0] sub_fu_241_p2;
wire  signed [29:0] grp_fu_333_p0;
wire   [29:0] tmp1_fu_338_p2;
wire   [29:0] tmp2_fu_348_p2;
wire   [31:0] tmp_3_fu_366_p3;
wire   [31:0] tmp_4_fu_378_p3;
wire   [31:0] tmp_5_fu_390_p3;
wire    ap_CS_fsm_state41;
wire    regslice_both_axis_pixel_out_V_data_V_U_apdone_blk;
reg   [40:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
reg    ap_ST_fsm_state29_blk;
reg    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
reg    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
reg    ap_ST_fsm_state40_blk;
reg    ap_ST_fsm_state41_blk;
reg   [31:0] axis_pixel_out_TDATA_int_regslice;
reg    axis_pixel_out_TVALID_int_regslice;
wire    axis_pixel_out_TREADY_int_regslice;
wire    regslice_both_axis_pixel_out_V_data_V_U_vld_out;
wire    regslice_both_axis_pixel_out_V_keep_V_U_apdone_blk;
reg   [3:0] axis_pixel_out_TKEEP_int_regslice;
wire    regslice_both_axis_pixel_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_axis_pixel_out_V_keep_V_U_vld_out;
wire    regslice_both_axis_pixel_out_V_strb_V_U_apdone_blk;
reg   [3:0] axis_pixel_out_TSTRB_int_regslice;
wire    regslice_both_axis_pixel_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_axis_pixel_out_V_strb_V_U_vld_out;
wire    regslice_both_axis_pixel_out_V_last_V_U_apdone_blk;
reg   [0:0] axis_pixel_out_TLAST_int_regslice;
wire    regslice_both_axis_pixel_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_axis_pixel_out_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 41'd1;
#0 grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_start_reg = 1'b0;
#0 grp_pixel_dma_in_Pipeline_2_fu_193_ap_start_reg = 1'b0;
#0 grp_pixel_dma_in_Pipeline_3_fu_201_ap_start_reg = 1'b0;
#0 grp_pixel_dma_in_Pipeline_4_fu_209_ap_start_reg = 1'b0;
#0 grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_start_reg = 1'b0;
end

pixel_dma_in_buf0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
buf0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buf0_address0),
    .ce0(buf0_ce0),
    .we0(buf0_we0),
    .d0(buf0_d0),
    .q0(buf0_q0)
);

pixel_dma_in_buf0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
buf1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buf1_address0),
    .ce0(buf1_ce0),
    .we0(buf1_we0),
    .d0(buf1_d0),
    .q0(buf1_q0)
);

pixel_dma_in_buf0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
buf2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buf2_address0),
    .ce0(buf2_ce0),
    .we0(buf2_we0),
    .d0(buf2_d0),
    .q0(buf2_q0)
);

pixel_dma_in_pixel_dma_in_Pipeline_VITIS_LOOP_71_2 grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_start),
    .ap_done(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_done),
    .ap_idle(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_idle),
    .ap_ready(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_ready),
    .m_axi_gmem_AWVALID(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .axis_pixel_out_TREADY(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TREADY),
    .buf2_address0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf2_address0),
    .buf2_ce0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf2_ce0),
    .buf2_we0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf2_we0),
    .buf2_d0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf2_d0),
    .buf1_address0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf1_address0),
    .buf1_ce0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf1_ce0),
    .buf1_we0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf1_we0),
    .buf1_d0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf1_d0),
    .buf0_address0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf0_address0),
    .buf0_ce0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf0_ce0),
    .buf0_we0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf0_we0),
    .buf0_d0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf0_d0),
    .trunc_ln(trunc_ln_reg_502),
    .empty_17(empty_36_reg_560),
    .axi_pixel_in(axi_pixel_in_read_reg_476),
    .empty(empty_35_reg_496),
    .add_ln72_6(add_ln72_6_reg_584),
    .axis_pixel_out_TDATA(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TDATA),
    .axis_pixel_out_TVALID(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TVALID),
    .axis_pixel_out_TKEEP(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TKEEP),
    .axis_pixel_out_TSTRB(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TSTRB),
    .axis_pixel_out_TLAST(grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TLAST)
);

pixel_dma_in_pixel_dma_in_Pipeline_2 grp_pixel_dma_in_Pipeline_2_fu_193(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_dma_in_Pipeline_2_fu_193_ap_start),
    .ap_done(grp_pixel_dma_in_Pipeline_2_fu_193_ap_done),
    .ap_idle(grp_pixel_dma_in_Pipeline_2_fu_193_ap_idle),
    .ap_ready(grp_pixel_dma_in_Pipeline_2_fu_193_ap_ready),
    .m_axi_gmem_AWVALID(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln93(trunc_ln4_reg_604),
    .buf0_address0(grp_pixel_dma_in_Pipeline_2_fu_193_buf0_address0),
    .buf0_ce0(grp_pixel_dma_in_Pipeline_2_fu_193_buf0_ce0),
    .buf0_we0(grp_pixel_dma_in_Pipeline_2_fu_193_buf0_we0),
    .buf0_d0(grp_pixel_dma_in_Pipeline_2_fu_193_buf0_d0)
);

pixel_dma_in_pixel_dma_in_Pipeline_3 grp_pixel_dma_in_Pipeline_3_fu_201(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_dma_in_Pipeline_3_fu_201_ap_start),
    .ap_done(grp_pixel_dma_in_Pipeline_3_fu_201_ap_done),
    .ap_idle(grp_pixel_dma_in_Pipeline_3_fu_201_ap_idle),
    .ap_ready(grp_pixel_dma_in_Pipeline_3_fu_201_ap_ready),
    .m_axi_gmem_AWVALID(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln94(trunc_ln5_reg_614),
    .buf1_address0(grp_pixel_dma_in_Pipeline_3_fu_201_buf1_address0),
    .buf1_ce0(grp_pixel_dma_in_Pipeline_3_fu_201_buf1_ce0),
    .buf1_we0(grp_pixel_dma_in_Pipeline_3_fu_201_buf1_we0),
    .buf1_d0(grp_pixel_dma_in_Pipeline_3_fu_201_buf1_d0)
);

pixel_dma_in_pixel_dma_in_Pipeline_4 grp_pixel_dma_in_Pipeline_4_fu_209(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_dma_in_Pipeline_4_fu_209_ap_start),
    .ap_done(grp_pixel_dma_in_Pipeline_4_fu_209_ap_done),
    .ap_idle(grp_pixel_dma_in_Pipeline_4_fu_209_ap_idle),
    .ap_ready(grp_pixel_dma_in_Pipeline_4_fu_209_ap_ready),
    .m_axi_gmem_AWVALID(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln95(trunc_ln6_reg_620),
    .buf2_address0(grp_pixel_dma_in_Pipeline_4_fu_209_buf2_address0),
    .buf2_ce0(grp_pixel_dma_in_Pipeline_4_fu_209_buf2_ce0),
    .buf2_we0(grp_pixel_dma_in_Pipeline_4_fu_209_buf2_we0),
    .buf2_d0(grp_pixel_dma_in_Pipeline_4_fu_209_buf2_d0)
);

pixel_dma_in_pixel_dma_in_Pipeline_VITIS_LOOP_97_4 grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_start),
    .ap_done(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_done),
    .ap_idle(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_idle),
    .ap_ready(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_ready),
    .axis_pixel_out_TREADY(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TREADY),
    .add_ln68(add_ln68_reg_532),
    .buf0_address0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf0_address0),
    .buf0_ce0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf0_ce0),
    .buf0_q0(buf0_q0),
    .axis_pixel_out_TDATA(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TDATA),
    .axis_pixel_out_TVALID(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TVALID),
    .axis_pixel_out_TKEEP(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TKEEP),
    .axis_pixel_out_TSTRB(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TSTRB),
    .axis_pixel_out_TLAST(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TLAST),
    .buf1_address0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf1_address0),
    .buf1_ce0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf1_ce0),
    .buf1_q0(buf1_q0),
    .buf2_address0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf2_address0),
    .buf2_ce0(grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf2_ce0),
    .buf2_q0(buf2_q0)
);

pixel_dma_in_AXI_Lite_1_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXI_LITE_1_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXI_LITE_1_DATA_WIDTH ))
AXI_Lite_1_s_axi_U(
    .AWVALID(s_axi_AXI_Lite_1_AWVALID),
    .AWREADY(s_axi_AXI_Lite_1_AWREADY),
    .AWADDR(s_axi_AXI_Lite_1_AWADDR),
    .WVALID(s_axi_AXI_Lite_1_WVALID),
    .WREADY(s_axi_AXI_Lite_1_WREADY),
    .WDATA(s_axi_AXI_Lite_1_WDATA),
    .WSTRB(s_axi_AXI_Lite_1_WSTRB),
    .ARVALID(s_axi_AXI_Lite_1_ARVALID),
    .ARREADY(s_axi_AXI_Lite_1_ARREADY),
    .ARADDR(s_axi_AXI_Lite_1_ARADDR),
    .RVALID(s_axi_AXI_Lite_1_RVALID),
    .RREADY(s_axi_AXI_Lite_1_RREADY),
    .RDATA(s_axi_AXI_Lite_1_RDATA),
    .RRESP(s_axi_AXI_Lite_1_RRESP),
    .BVALID(s_axi_AXI_Lite_1_BVALID),
    .BREADY(s_axi_AXI_Lite_1_BREADY),
    .BRESP(s_axi_AXI_Lite_1_BRESP),
    .ACLK(axi_lite_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .axi_pixel_in(axi_pixel_in),
    .frame_width(frame_width),
    .frame_height(frame_height),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .clk(ap_clk),
    .rst(ap_rst_n_axi_lite_clk_inv)
);

pixel_dma_in_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_DW( 32 ),
    .USER_AW( 32 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARLEN(gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(1'b0)
);

pixel_dma_in_mul_30s_30s_30_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
mul_30s_30s_30_5_1_U31(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_333_p0),
    .din1(empty_35_reg_496),
    .ce(1'b1),
    .dout(grp_fu_333_p2)
);

pixel_dma_in_regslice_both #(
    .DataWidth( 32 ))
regslice_both_axis_pixel_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axis_pixel_out_TDATA_int_regslice),
    .vld_in(axis_pixel_out_TVALID_int_regslice),
    .ack_in(axis_pixel_out_TREADY_int_regslice),
    .data_out(axis_pixel_out_TDATA),
    .vld_out(regslice_both_axis_pixel_out_V_data_V_U_vld_out),
    .ack_out(axis_pixel_out_TREADY),
    .apdone_blk(regslice_both_axis_pixel_out_V_data_V_U_apdone_blk)
);

pixel_dma_in_regslice_both #(
    .DataWidth( 4 ))
regslice_both_axis_pixel_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axis_pixel_out_TKEEP_int_regslice),
    .vld_in(axis_pixel_out_TVALID_int_regslice),
    .ack_in(regslice_both_axis_pixel_out_V_keep_V_U_ack_in_dummy),
    .data_out(axis_pixel_out_TKEEP),
    .vld_out(regslice_both_axis_pixel_out_V_keep_V_U_vld_out),
    .ack_out(axis_pixel_out_TREADY),
    .apdone_blk(regslice_both_axis_pixel_out_V_keep_V_U_apdone_blk)
);

pixel_dma_in_regslice_both #(
    .DataWidth( 4 ))
regslice_both_axis_pixel_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axis_pixel_out_TSTRB_int_regslice),
    .vld_in(axis_pixel_out_TVALID_int_regslice),
    .ack_in(regslice_both_axis_pixel_out_V_strb_V_U_ack_in_dummy),
    .data_out(axis_pixel_out_TSTRB),
    .vld_out(regslice_both_axis_pixel_out_V_strb_V_U_vld_out),
    .ack_out(axis_pixel_out_TREADY),
    .apdone_blk(regslice_both_axis_pixel_out_V_strb_V_U_apdone_blk)
);

pixel_dma_in_regslice_both #(
    .DataWidth( 1 ))
regslice_both_axis_pixel_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axis_pixel_out_TLAST_int_regslice),
    .vld_in(axis_pixel_out_TVALID_int_regslice),
    .ack_in(regslice_both_axis_pixel_out_V_last_V_U_ack_in_dummy),
    .data_out(axis_pixel_out_TLAST),
    .vld_out(regslice_both_axis_pixel_out_V_last_V_U_vld_out),
    .ack_out(axis_pixel_out_TREADY),
    .apdone_blk(regslice_both_axis_pixel_out_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_dma_in_Pipeline_2_fu_193_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_pixel_dma_in_Pipeline_2_fu_193_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_dma_in_Pipeline_2_fu_193_ap_ready == 1'b1)) begin
            grp_pixel_dma_in_Pipeline_2_fu_193_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_dma_in_Pipeline_3_fu_201_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state28)) begin
            grp_pixel_dma_in_Pipeline_3_fu_201_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_dma_in_Pipeline_3_fu_201_ap_ready == 1'b1)) begin
            grp_pixel_dma_in_Pipeline_3_fu_201_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_dma_in_Pipeline_4_fu_209_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state37)) begin
            grp_pixel_dma_in_Pipeline_4_fu_209_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_dma_in_Pipeline_4_fu_209_ap_ready == 1'b1)) begin
            grp_pixel_dma_in_Pipeline_4_fu_209_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_ready == 1'b1)) begin
            grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state39)) begin
            grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_start_reg <= 1'b1;
        end else if ((grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_ready == 1'b1)) begin
            grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_116 <= 32'd0;
    end else if (((1'b0 == ap_block_state40_on_subcall_done) & (1'b1 == ap_CS_fsm_state40))) begin
        i_fu_116 <= indvars_iv_next262_reg_550;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln68_1_reg_522 <= add_ln68_1_fu_289_p2;
        and_ln_reg_517[29 : 5] <= and_ln_fu_282_p3[29 : 5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln68_reg_532 <= add_ln68_fu_299_p2;
        cmp46_reg_528 <= cmp46_fu_294_p2;
        shl_ln_reg_537[29 : 1] <= shl_ln_fu_304_p3[29 : 1];
        tmp_reg_542 <= tmp_fu_311_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln72_6_reg_584 <= add_ln72_6_fu_362_p2;
        empty_37_reg_569 <= empty_37_fu_343_p2;
        empty_39_reg_574 <= empty_39_fu_353_p2;
        empty_41_reg_579 <= empty_41_fu_358_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        axi_pixel_in_read_reg_476 <= axi_pixel_in;
        empty_34_reg_490 <= empty_34_fu_237_p1;
        empty_35_reg_496 <= empty_35_fu_247_p2;
        empty_reg_484 <= empty_fu_233_p1;
        frame_height_read_reg_471 <= frame_height;
        tmp_2_reg_512 <= {{empty_35_fu_247_p2[29:5]}};
        trunc_ln68_reg_507 <= trunc_ln68_fu_263_p1;
        trunc_ln_reg_502 <= {{sub_fu_241_p2[31:5]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        empty_36_reg_560 <= grp_fu_333_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        empty_38_reg_589 <= empty_38_fu_373_p2;
        empty_40_reg_594 <= empty_40_fu_385_p2;
        empty_42_reg_599 <= empty_42_fu_397_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        indvars_iv_next262_reg_550 <= indvars_iv_next262_fu_323_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (cmp46_reg_528 == 1'd0))) begin
        trunc_ln4_reg_604 <= {{empty_42_reg_599[31:2]}};
        trunc_ln5_reg_614 <= {{empty_40_reg_594[31:2]}};
        trunc_ln6_reg_620 <= {{empty_38_reg_589[31:2]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state12_io)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_pixel_dma_in_Pipeline_2_fu_193_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

always @ (*) begin
    if ((grp_pixel_dma_in_Pipeline_3_fu_201_ap_done == 1'b0)) begin
        ap_ST_fsm_state29_blk = 1'b1;
    end else begin
        ap_ST_fsm_state29_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state30_blk = 1'b1;
    end else begin
        ap_ST_fsm_state30_blk = 1'b0;
    end
end

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

always @ (*) begin
    if ((grp_pixel_dma_in_Pipeline_4_fu_209_ap_done == 1'b0)) begin
        ap_ST_fsm_state38_blk = 1'b1;
    end else begin
        ap_ST_fsm_state38_blk = 1'b0;
    end
end

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state40_on_subcall_done)) begin
        ap_ST_fsm_state40_blk = 1'b1;
    end else begin
        ap_ST_fsm_state40_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_axis_pixel_out_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state41_blk = 1'b1;
    end else begin
        ap_ST_fsm_state41_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((regslice_both_axis_pixel_out_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state41))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_axis_pixel_out_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state41))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state40) & (cmp46_reg_528 == 1'd0))) begin
        axis_pixel_out_TDATA_int_regslice = grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TDATA;
    end else if (((grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        axis_pixel_out_TDATA_int_regslice = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TDATA;
    end else begin
        axis_pixel_out_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state40) & (cmp46_reg_528 == 1'd0))) begin
        axis_pixel_out_TKEEP_int_regslice = grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TKEEP;
    end else if (((grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        axis_pixel_out_TKEEP_int_regslice = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TKEEP;
    end else begin
        axis_pixel_out_TKEEP_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state40) & (cmp46_reg_528 == 1'd0))) begin
        axis_pixel_out_TLAST_int_regslice = grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TLAST;
    end else if (((grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        axis_pixel_out_TLAST_int_regslice = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TLAST;
    end else begin
        axis_pixel_out_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state40) & (cmp46_reg_528 == 1'd0))) begin
        axis_pixel_out_TSTRB_int_regslice = grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TSTRB;
    end else if (((grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        axis_pixel_out_TSTRB_int_regslice = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TSTRB;
    end else begin
        axis_pixel_out_TSTRB_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) & (cmp46_reg_528 == 1'd0))) begin
        axis_pixel_out_TVALID_int_regslice = grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        axis_pixel_out_TVALID_int_regslice = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TVALID;
    end else begin
        axis_pixel_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) & (cmp46_reg_528 == 1'd0))) begin
        buf0_address0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf0_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        buf0_address0 = grp_pixel_dma_in_Pipeline_2_fu_193_buf0_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf0_address0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf0_address0;
    end else begin
        buf0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) & (cmp46_reg_528 == 1'd0))) begin
        buf0_ce0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        buf0_ce0 = grp_pixel_dma_in_Pipeline_2_fu_193_buf0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf0_ce0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf0_ce0;
    end else begin
        buf0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        buf0_d0 = grp_pixel_dma_in_Pipeline_2_fu_193_buf0_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf0_d0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf0_d0;
    end else begin
        buf0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        buf0_we0 = grp_pixel_dma_in_Pipeline_2_fu_193_buf0_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf0_we0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf0_we0;
    end else begin
        buf0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) & (cmp46_reg_528 == 1'd0))) begin
        buf1_address0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf1_address0;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        buf1_address0 = grp_pixel_dma_in_Pipeline_3_fu_201_buf1_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf1_address0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf1_address0;
    end else begin
        buf1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) & (cmp46_reg_528 == 1'd0))) begin
        buf1_ce0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        buf1_ce0 = grp_pixel_dma_in_Pipeline_3_fu_201_buf1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf1_ce0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf1_ce0;
    end else begin
        buf1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        buf1_d0 = grp_pixel_dma_in_Pipeline_3_fu_201_buf1_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf1_d0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf1_d0;
    end else begin
        buf1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        buf1_we0 = grp_pixel_dma_in_Pipeline_3_fu_201_buf1_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf1_we0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf1_we0;
    end else begin
        buf1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) & (cmp46_reg_528 == 1'd0))) begin
        buf2_address0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf2_address0;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        buf2_address0 = grp_pixel_dma_in_Pipeline_4_fu_209_buf2_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf2_address0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf2_address0;
    end else begin
        buf2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) & (cmp46_reg_528 == 1'd0))) begin
        buf2_ce0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_buf2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        buf2_ce0 = grp_pixel_dma_in_Pipeline_4_fu_209_buf2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf2_ce0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf2_ce0;
    end else begin
        buf2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        buf2_d0 = grp_pixel_dma_in_Pipeline_4_fu_209_buf2_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf2_d0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf2_d0;
    end else begin
        buf2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        buf2_we0 = grp_pixel_dma_in_Pipeline_4_fu_209_buf2_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf2_we0 = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_buf2_we0;
    end else begin
        buf2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
        gmem_ARADDR = sext_ln95_fu_450_p1;
    end else if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        gmem_ARADDR = sext_ln94_fu_440_p1;
    end else if (((1'b0 == ap_block_state12_io) & (1'b1 == ap_CS_fsm_state12) & (cmp46_reg_528 == 1'd0))) begin
        gmem_ARADDR = sext_ln93_fu_411_p1;
    end else if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37))) begin
        gmem_ARADDR = grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_ARADDR = grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19))) begin
        gmem_ARADDR = grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARADDR = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state30)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state21)) | ((1'b0 == ap_block_state12_io) & (1'b1 == ap_CS_fsm_state12) & (cmp46_reg_528 == 1'd0)))) begin
        gmem_ARLEN = 32'd32;
    end else if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37))) begin
        gmem_ARLEN = grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_ARLEN = grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19))) begin
        gmem_ARLEN = grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARLEN = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state30)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state21)) | ((1'b0 == ap_block_state12_io) & (1'b1 == ap_CS_fsm_state12) & (cmp46_reg_528 == 1'd0)))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37))) begin
        gmem_ARVALID = grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_ARVALID = grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19))) begin
        gmem_ARVALID = grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_ARVALID = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37))) begin
        gmem_RREADY = grp_pixel_dma_in_Pipeline_4_fu_209_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_RREADY = grp_pixel_dma_in_Pipeline_3_fu_201_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19))) begin
        gmem_RREADY = grp_pixel_dma_in_Pipeline_2_fu_193_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_RREADY = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state21) | ((1'b1 == ap_CS_fsm_state12) & (cmp46_reg_528 == 1'd0)))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln68_fu_318_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b0 == ap_block_state12_io) & (1'b1 == ap_CS_fsm_state12) & (cmp46_reg_528 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else if (((1'b0 == ap_block_state12_io) & (1'b1 == ap_CS_fsm_state12) & (cmp46_reg_528 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_pixel_dma_in_Pipeline_2_fu_193_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((grp_pixel_dma_in_Pipeline_3_fu_201_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state30 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            if (((grp_pixel_dma_in_Pipeline_4_fu_209_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state38))) begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            if (((1'b0 == ap_block_state40_on_subcall_done) & (1'b1 == ap_CS_fsm_state40))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end
        end
        ap_ST_fsm_state41 : begin
            if (((regslice_both_axis_pixel_out_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state41))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln68_1_fu_289_p2 = (and_ln_fu_282_p3 + empty_34_reg_490);

assign add_ln68_fu_299_p2 = (empty_reg_484 + 5'd2);

assign add_ln72_6_fu_362_p2 = (shl_ln_reg_537 + empty_36_reg_560);

assign and_ln_fu_282_p3 = {{tmp_2_reg_512}, {5'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state12_io = ((gmem_ARREADY == 1'b0) & (cmp46_reg_528 == 1'd0));
end

always @ (*) begin
    ap_block_state40_on_subcall_done = ((grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_done == 1'b0) & (cmp46_reg_528 == 1'd0));
end

always @ (*) begin
    ap_rst_n_axi_lite_clk_inv = ~ap_rst_n_axi_lite_clk;
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign axis_pixel_out_TVALID = regslice_both_axis_pixel_out_V_data_V_U_vld_out;

assign cmp46_fu_294_p2 = ((empty_reg_484 == 5'd30) ? 1'b1 : 1'b0);

assign empty_34_fu_237_p1 = frame_width[29:0];

assign empty_35_fu_247_p2 = (empty_34_fu_237_p1 + 30'd2);

assign empty_37_fu_343_p2 = (tmp1_fu_338_p2 + tmp_reg_542);

assign empty_38_fu_373_p2 = (tmp_3_fu_366_p3 + axi_pixel_in_read_reg_476);

assign empty_39_fu_353_p2 = (tmp2_fu_348_p2 + add_ln68_1_reg_522);

assign empty_40_fu_385_p2 = (tmp_4_fu_378_p3 + axi_pixel_in_read_reg_476);

assign empty_41_fu_358_p2 = (empty_36_reg_560 + and_ln_reg_517);

assign empty_42_fu_397_p2 = (tmp_5_fu_390_p3 + axi_pixel_in_read_reg_476);

assign empty_fu_233_p1 = frame_width[4:0];

assign grp_fu_333_p0 = i_fu_116[29:0];

assign grp_pixel_dma_in_Pipeline_2_fu_193_ap_start = grp_pixel_dma_in_Pipeline_2_fu_193_ap_start_reg;

assign grp_pixel_dma_in_Pipeline_3_fu_201_ap_start = grp_pixel_dma_in_Pipeline_3_fu_201_ap_start_reg;

assign grp_pixel_dma_in_Pipeline_4_fu_209_ap_start = grp_pixel_dma_in_Pipeline_4_fu_209_ap_start_reg;

assign grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_start = grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_ap_start_reg;

assign grp_pixel_dma_in_Pipeline_VITIS_LOOP_71_2_fu_171_axis_pixel_out_TREADY = (axis_pixel_out_TREADY_int_regslice & ap_CS_fsm_state11);

assign grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_start = grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_ap_start_reg;

assign grp_pixel_dma_in_Pipeline_VITIS_LOOP_97_4_fu_217_axis_pixel_out_TREADY = (axis_pixel_out_TREADY_int_regslice & ap_CS_fsm_state40);

assign icmp_ln68_fu_318_p2 = ((i_fu_116 == frame_height_read_reg_471) ? 1'b1 : 1'b0);

assign indvars_iv_next262_fu_323_p2 = (i_fu_116 + 32'd1);

assign sext_ln93_fu_411_p1 = trunc_ln4_fu_402_p4;

assign sext_ln94_fu_440_p1 = $signed(trunc_ln5_reg_614);

assign sext_ln95_fu_450_p1 = $signed(trunc_ln6_reg_620);

assign shl_ln_fu_304_p3 = {{trunc_ln68_reg_507}, {1'd0}};

assign sub_fu_241_p2 = (frame_width + 32'd2);

assign tmp1_fu_338_p2 = (empty_36_reg_560 + 30'd4);

assign tmp2_fu_348_p2 = (empty_36_reg_560 + 30'd2);

assign tmp_3_fu_366_p3 = {{empty_37_reg_569}, {2'd0}};

assign tmp_4_fu_378_p3 = {{empty_39_reg_574}, {2'd0}};

assign tmp_5_fu_390_p3 = {{empty_41_reg_579}, {2'd0}};

assign tmp_fu_311_p2 = (empty_34_reg_490 + add_ln68_1_reg_522);

assign trunc_ln4_fu_402_p4 = {{empty_42_reg_599[31:2]}};

assign trunc_ln68_fu_263_p1 = frame_width[28:0];

always @ (posedge ap_clk) begin
    and_ln_reg_517[4:0] <= 5'b00000;
    shl_ln_reg_537[0] <= 1'b0;
end


reg find_kernel_block = 0;
// synthesis translate_off
`include "pixel_dma_in_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //pixel_dma_in

