
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xpixel_dma_out.h"

/*
* The configuration table for devices
*/

XPixel_dma_out_Config XPixel_dma_out_ConfigTable[XPAR_XPIXEL_DMA_OUT_NUM_INSTANCES] =
{
	{
		XPAR_PIXEL_DMA_OUT_0_DEVICE_ID,
		XPAR_PIXEL_DMA_OUT_0_S_AXI_AXI_LITE_1_BASEADDR
	}
};


